

# Configuración de la base de datos
db.motor = postgresql
db.host = ep-red-heart-amsemalv.c-5.us-east-1.aws.neon.tech
db.puerto = 5432
db.nombre = neondb
db.usuario = neondb_owner
db.password = npg_ejJC29rlqPNd
db.schema = Tallercorte2
db.ssl = true
db.timeout_conexion = 30
db.zona_horaria = America/Bogota